name: hotel_booking

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  dots_indicator: ^4.0.1
  image_picker: ^1.0.7
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  velocity_x: ^4.1.1
  flutter_screenutil: ^5.9.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.1
  flutter_credit_card: ^4.0.1
  ticket_widget: ^1.0.2
  intl_phone_field: ^3.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.2
  intl: ^0.19.0
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  cached_network_image: ^3.3.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/logo/logo.png"
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
  web:
    generate: true
    image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/login_screen/
    - assets/images/register_screen/
    - assets/images/forgot_password/
    - assets/images/bottom_Bar/
    - assets/images/home/
    - assets/images/notification/
    - assets/images/search/
    - assets/images/filterHotel/
    - assets/images/hotelDetail/
    - assets/images/payment/
    - assets/images/profile/
    - assets/images/myBooking/
    - assets/images/helpCenter/
    - assets/fonts/
    - assets/data/
    - assets/icon/
    - assets/logo/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400